### ISSUE TITLE
Astaire crashes when terminated (with no output to its log file)

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/astaire#14]
Saw the following in syslog when upgrading astaire:

```
Apr 14 10:10:50 ec2-54-91-213-116 astaire[11977]: 7003 - Description: Astaire ended - Termination signal received - terminating. @@Cause: Astaire has been terminated by Monit or has exited. @@Effect: The Astaire service is not longer available. @@Action: (1). This occurs normally when Astaire is stopped. (2). If Astaire hit an internal error then monit can restart Astaire.
... <snip> ...
Apr 14 10:10:57 ec2-54-91-213-116 kernel: [12750838.184955] astaire[12165]: segfault at 18 ip 000000000041fc40 sp 00007fffd4018ad0 error 4 in astaire[400000+2c000]
```

However the log file was clean:
```
14-04-2015 10:10:50.202 UTC Info astaire.cpp:468: No resyncing required
14-04-2015 10:10:50.202 UTC Debug updater.h:91: Started updater thread
14-04-2015 10:10:50.202 UTC Debug updater.h:91: Started updater thread
14-04-2015 10:10:50.202 UTC Error memcached_tap_client.cpp:359: Failed to connect to 10.240.34.210:11211 (111)
14-04-2015 10:10:50.202 UTC Verbose astaire.cpp:879: Failed to connect to local server 10.240.34.210:11211, error was (111)
14-04-2015 10:10:50.202 UTC Error memcached_tap_client.cpp:359: Failed to connect to 10.240.34.210:11211 (111)
14-04-2015 10:10:50.202 UTC Verbose astaire.cpp:879: Failed to connect to local server 10.240.34.210:11211, error was (111)
14-04-2015 10:10:50.202 UTC Debug astaire.cpp:200: Wait for resync trigger
14-04-2015 10:10:50.232 UTC Debug zmq_lvc.cpp:206: New subscription for astaire_global
14-04-2015 10:10:50.245 UTC Debug zmq_lvc.cpp:213: Statistic found, check for cached value
14-04-2015 10:10:50.245 UTC Debug zmq_lvc.cpp:285: Replaying cache for entry 0x7f6e1c0008c0 (length: 7)
14-04-2015 10:10:50.245 UTC Debug zmq_lvc.cpp:206: New subscription for astaire_connections
14-04-2015 10:10:50.245 UTC Debug zmq_lvc.cpp:213: Statistic found, check for cached value
14-04-2015 10:10:50.245 UTC Debug zmq_lvc.cpp:285: Replaying cache for entry 0x7f6e1c005330 (length: 2)
14-04-2015 10:10:50.605 UTC Info main.cpp:298: Astaire shutting down
14-04-2015 10:10:50.605 UTC Debug statistic.cpp:103: Send new value for statistic astaire_global, size 5
14-04-2015 10:10:50.605 UTC Debug zmq_lvc.cpp:172: Update to astaire_global statistic
14-04-2015 10:10:50.605 UTC Debug zmq_lvc.cpp:256: Clearing message cache for 0x7f6e1c0008c0
14-04-2015 10:10:51.610 UTC Debug zmq_lvc.cpp:256: Clearing message cache for 0x7f6e1c0008c0
14-04-2015 10:10:51.610 UTC Debug zmq_lvc.cpp:256: Clearing message cache for 0x7f6e1c005330
14-04-2015 10:10:51.611 UTC Debug zmq_lvc.cpp:110: Unbinding and closing statistics socket inproc://astaire_global
14-04-2015 10:10:51.611 UTC Debug zmq_lvc.cpp:110: Unbinding and closing statistics socket inproc://astaire_connections
14-04-2015 10:11:04.423 UTC Status main.cpp:231: Log level set to 5
14-04-2015 10:11:04.423 UTC Info main.cpp:240: Command-line options were: /usr/share/clearwater/bin/astaire --local-name=10.240.34.210:11211 --cluster-settings-file=/etc/clearwater/cluster_settings --log-file=/var/log/astaire --log-level=5 --alarms-enabled
14-04-2015 10:11:04.423 UTC Status main.cpp:260: Astaire starting up
14-04-2015 10:11:04.425 UTC Debug alarm.cpp:76: astaire cleared its alarms
14-04-2015 10:11:04.425 UTC Debug zmq_lvc.cpp:68: Initializing statistics aggregator
14-04-2015 10:11:04.425 UTC Debug zmq_lvc.cpp:84: Opened statistics socket inproc://astaire_global
14-04-2015 10:11:04.425 UTC Debug zmq_lvc.cpp:84: Opened statistics socket inproc://astaire_connections
14-04-2015 10:11:04.425 UTC Debug statistic.cpp:48: Creating astaire_global statistic reporter
14-04-2015 10:11:04.425 UTC Debug statistic.cpp:48: Creating astaire_connections statistic reporter
14-04-2015 10:11:04.425 UTC Debug updater.h:56: Created updater
```

I don't have a core file as my node ran out of disk space.

**Comment by AlexHockey** [comment]
It looks like this only happens after an initial install / upgrade.

**Comment by AlexHockey** [comment]
It looks like we are crashing in startup when initializing the SIGHUP signal handler. The signal is already hooked and we try to log this fact, only to find the logger hasn't been initialized yet. But why has the signal already been hooked?

```
#0  0x000000000041fc40 in Log::_write (level=<optimized out>, module=<optimized out>, line_number=95, fmt=0x424ce7 "SIGNAL already hooked", args=<optimized out>)
    at /mnt/extra/alex/src/astaire/modules/cpp-common/src/log.cpp:150
150     /mnt/extra/alex/src/astaire/modules/cpp-common/src/log.cpp: No such file or directory.
(gdb) bt
#0  0x000000000041fc40 in Log::_write (level=<optimized out>, module=<optimized out>, line_number=95, fmt=0x424ce7 "SIGNAL already hooked", args=<optimized out>)
    at /mnt/extra/alex/src/astaire/modules/cpp-common/src/log.cpp:150
#1  0x000000000041fd5d in Log::write (level=<optimized out>, module=<optimized out>, line_number=<optimized out>, fmt=<optimized out>) at /mnt/extra/alex/src/astaire/modules/cpp-common/src/log.cpp:91
#2  0x000000000041de6f in SignalHandler<1>::SignalHandler (this=0x62cbc0) at /mnt/extra/alex/src/astaire/modules/cpp-common/include/signalhandler.h:95
#3  0x000000000040570e in __static_initialization_and_destruction_0 (__priority=65535, __initialize_p=1) at /mnt/extra/alex/src/astaire/modules/cpp-common/src/signalhandler.cpp:41
#4  _GLOBAL__sub_I__sighup_handler () at /mnt/extra/alex/src/astaire/modules/cpp-common/src/signalhandler.cpp:42
#5  0x000000000042276d in __libc_csu_init ()
#6  0x00007f23e09f4700 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x0000000000406afd in _start ()
(gdb) p Log::logger
$1 = (Logger *) 0x62cd60
(gdb) p *Log::logger
$2 = {_vptr.Logger = 0x0, static ADD_TIMESTAMPS = 1, static FLUSH_ON_WRITE = 2, _flags = 0, _prefix = {static npos = <optimized out>,
    _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x0}}, _last_hour = 0, _rotate = false, _fd = 0x0, _discards = 0, _saved_errno = 0, _lock = {
    __data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, static LOGFILE_CHECK_FREQUENCY = 1000}
(gdb) p Log::logger->_fd
$3 = (FILE *) 0x0
```

**Comment by AlexHockey** [comment]
Got it (after discussion with Andy). Signal actions are inherited from your parent, and astaire doesn't have the option to make dpkg not start it. So it appears that dpkg ignores SIGHUP which gets inherited when it spawns astaire.
