### ISSUE TITLE
Astaire crashes on stop

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/astaire#62]
#### Symptoms
Stopping Astaire causes it to crash

```
21-04-2016 14:16:52.168 UTC Info alarm.cpp:297: Reraising alarms thread terminating

Signal 11 caught

Basic stack dump:
/usr/share/clearwater/bin/astaire[0x422e6d]
/usr/share/clearwater/bin/astaire[0x42402d]
/usr/share/clearwater/bin/astaire[0x42703c]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x7f793086ed40]
/lib/x86_64-linux-gnu/libpthread.so.0(pthread_cancel+0xd)[0x7f793199e70d]
/usr/share/clearwater/bin/astaire[0x420680]
/lib/x86_64-linux-gnu/libc.so.6(+0x3c259)[0x7f7930874259]
/lib/x86_64-linux-gnu/libc.so.6(+0x3c2a5)[0x7f79308742a5]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfc)[0x7f7930859ecc]
/usr/share/clearwater/bin/astaire[0x4090be]

Advanced stack dump (requires gdb):
[New LWP 1458]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f79308f8b99 in __libc_waitpid (pid=1550, stat_loc=stat_loc@entry=0x7fff672a1420, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
40      ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.

Thread 2 (Thread 0x7f79267fc700 (LWP 1458)):
#0  0x00007f79319a06dd in accept () at ../sysdeps/unix/syscall-template.S:81
#1  0x0000000000428672 in ProxyServer::listen_thread_fn (this=0x1a573f0) at proxy_server.cpp:160
#2  0x0000000000428a39 in ProxyServer::listen_thread_entry_point (server_param=<optimized out>) at proxy_server.cpp:147
#3  0x00007f7931999182 in start_thread (arg=0x7f79267fc700) at pthread_create.c:312
#4  0x00007f793093247d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7f7932002780 (LWP 1446)):
#0  0x00007f79308f8b99 in __libc_waitpid (pid=1550, stat_loc=stat_loc@entry=0x7fff672a1420, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
#1  0x00007f793087e2e2 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:148
#2  0x0000000000422f23 in Logger::backtrace (this=0x1a4b1f0, data=<optimized out>) at ../modules/cpp-common/src/logger.cpp:318
#3  0x000000000042402d in Log::backtrace (fmt=fmt@entry=0x4305d8 "Signal %d caught") at ../modules/cpp-common/src/log.cpp:185
#4  0x000000000042703c in signal_handler (sig=11) at main.cpp:202
#5  <signal handler called>
#6  0x00007f793199e70d in pthread_cancel (th=140158476113664) at pthread_cancel.c:34
#7  0x0000000000420680 in SignalHandler<1>::~SignalHandler (this=0x63bd70 <_sighup_handler>, __in_chrg=<optimized out>) at ../modules/cpp-common/include/signalhandler.h:106
#8  0x00007f7930874259 in __run_exit_handlers (status=0, listp=0x7f7930bf66c8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#9  0x00007f79308742a5 in __GI_exit (status=<optimized out>) at exit.c:104
#10 0x00007f7930859ecc in __libc_start_main (main=0x407520 <main(int, char**)>, argc=7, argv=0x7fff672a3e68, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff672a3e58) at libc-start.c:321
#11 0x00000000004090be in _start ()
```

#### Impact
This triggers the diags-monitor to collect diags, which costs CPU/disk space. Also, crashes are bad.

**Comment by eleanor-merry** [comment]
This isn't in release-94-fixes
