### ISSUE TITLE
Astaire crashes in the FV tests

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/astaire#70]
#### Symptoms
Clearwater-fv-test intermittently fails because astaire crashes.

```
[ RUN      ] MemcachedSolutionFailureTest/1.AddDeleteKill
[       OK ] MemcachedSolutionFailureTest/1.AddDeleteKill (2006 ms)
[ RUN      ] MemcachedSolutionFailureTest/1.AddKillCASDelete
[       OK ] MemcachedSolutionFailureTest/1.AddKillCASDelete (2030 ms)

Signal 11 caught

Basic stack dump:
astaire[0x422e6d]
astaire[0x42402d]
astaire[0x42703c]
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40)[0x2aaf9c1e0d40]
/lib/x86_64-linux-gnu/libpthread.so.0(pthread_mutex_lock+0x4)[0x2aaf9b202414]
astaire[0x426165]
astaire[0x426681]
astaire[0x426aa2]
astaire[0x426b89]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8182)[0x2aaf9b200182]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x2aaf9c2a447d]

Advanced stack dump (requires gdb):
Could not attach to process.  If your uid matches the uid of the target process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
<http://repo.cw-ngv.com:8080/job/clearwater-fv-test/ws/src/2239>: No such file or directory.
```

#### Steps to reproduce
Run the clearwater-fv-tests repeatedly

**Comment by richardwhiuk** [comment]
Stack is:

```
(gdb) bt
#0  0x00002b7bbf6c4cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00002b7bbf6c80d8 in __GI_abort () at abort.c:89
#2  0x000000000042705a in signal_handler (sig=11) at main.cpp:211
#3  <signal handler called>
#4  __GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:66
#5  0x0000000000426165 in push_noblock (item=<error reading variable: access outside bounds of object referenced via synthetic pointer>, this=0x0)
    at ../modules/cpp-common/include/eventq.h:239
#6  AlarmReqAgent::alarm_request (this=this@entry=0x63bfc0 <AlarmReqAgent::_instance>, req=std::vector of length 3, capacity 3 = {...})
    at ../modules/cpp-common/src/alarm.cpp:358
#7  0x0000000000426681 in AlarmState::issue (this=0x1513560) at ../modules/cpp-common/src/alarm.cpp:71
#8  0x0000000000426aa2 in reraise_last_state (this=<optimized out>) at ../modules/cpp-common/src/alarm.cpp:103
#9  AlarmManager::reraise_alarms (this=0x1513620) at ../modules/cpp-common/src/alarm.cpp:257
#10 0x0000000000426b89 in AlarmManager::reraise_alarms_function (data=<optimized out>) at ../modules/cpp-common/src/alarm.cpp:225
#11 0x00002b7bbe6e4182 in start_thread (arg=0x2b7bc05a7700) at pthread_create.c:312
```

**Comment by richardwhiuk** [comment]
This is fixed in https://github.com/Metaswitch/cpp-common/issues/521 but clearwater-fv-test is tracking an old version of astaire. I'll fix that up.

**Comment by richardwhiuk** [comment]
Fixed in https://github.com/Metaswitch/clearwater-fv-test/commit/1ffc431bff82c0b4cbc8c685d85deef348a77326
